[2021-02-19 07:39:32,814] {scheduler_job.py:182} INFO - Started process (PID=157) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:39:32,815] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:39:32,816] {logging_mixin.py:104} INFO - [2021-02-19 07:39:32,816] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:39:32,890] {logging_mixin.py:104} INFO - [2021-02-19 07:39:32,818] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 17
    task_id="bash",}
                   ^
SyntaxError: invalid syntax
[2021-02-19 07:39:32,891] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:39:33,110] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.301 seconds
[2021-02-19 07:40:03,304] {scheduler_job.py:182} INFO - Started process (PID=183) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:40:03,331] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:40:03,333] {logging_mixin.py:104} INFO - [2021-02-19 07:40:03,332] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:40:03,337] {logging_mixin.py:104} INFO - [2021-02-19 07:40:03,335] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 17
    task_id="bash",}
                   ^
SyntaxError: invalid syntax
[2021-02-19 07:40:03,338] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:40:03,400] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.102 seconds
[2021-02-19 07:40:33,647] {scheduler_job.py:182} INFO - Started process (PID=193) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:40:33,666] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:40:33,667] {logging_mixin.py:104} INFO - [2021-02-19 07:40:33,667] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:40:33,697] {logging_mixin.py:104} INFO - [2021-02-19 07:40:33,669] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 17
    task_id="bash",}
                   ^
SyntaxError: invalid syntax
[2021-02-19 07:40:33,698] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:40:33,758] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.116 seconds
[2021-02-19 07:41:29,239] {scheduler_job.py:182} INFO - Started process (PID=154) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:41:29,256] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:41:29,257] {logging_mixin.py:104} INFO - [2021-02-19 07:41:29,257] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:41:29,269] {logging_mixin.py:104} INFO - [2021-02-19 07:41:29,267] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 13, in <module>
    default_args=default_args
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2021-02-19 07:41:29,269] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:41:29,365] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.132 seconds
[2021-02-19 07:41:59,566] {scheduler_job.py:182} INFO - Started process (PID=165) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:41:59,568] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:41:59,569] {logging_mixin.py:104} INFO - [2021-02-19 07:41:59,569] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:41:59,579] {logging_mixin.py:104} INFO - [2021-02-19 07:41:59,578] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 13, in <module>
    default_args=default_args
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2021-02-19 07:41:59,580] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:41:59,649] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.089 seconds
[2021-02-19 07:42:51,998] {scheduler_job.py:182} INFO - Started process (PID=157) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:42:52,015] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:42:52,016] {logging_mixin.py:104} INFO - [2021-02-19 07:42:52,016] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:42:52,111] {logging_mixin.py:104} INFO - [2021-02-19 07:42:52,084] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 18, in <module>
    bash_command="echo 1"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 89, in __call__
    obj: BaseOperator = type.__call__(cls, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 122, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 487, in __init__
    self.dag = dag or DagContext.get_current_dag()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 593, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 644, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 1589, in add_task
    raise AirflowException("Task is missing the start_date parameter")
airflow.exceptions.AirflowException: Task is missing the start_date parameter
[2021-02-19 07:42:52,112] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:42:52,201] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.210 seconds
[2021-02-19 07:43:22,332] {scheduler_job.py:182} INFO - Started process (PID=165) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:43:22,334] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:43:22,335] {logging_mixin.py:104} INFO - [2021-02-19 07:43:22,335] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:43:22,346] {logging_mixin.py:104} INFO - [2021-02-19 07:43:22,342] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 18, in <module>
    bash_command="echo 1"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 89, in __call__
    obj: BaseOperator = type.__call__(cls, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 122, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 487, in __init__
    self.dag = dag or DagContext.get_current_dag()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 593, in __setattr__
    super().__setattr__(key, value)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 644, in dag
    dag.add_task(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 1589, in add_task
    raise AirflowException("Task is missing the start_date parameter")
airflow.exceptions.AirflowException: Task is missing the start_date parameter
[2021-02-19 07:43:22,347] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:43:22,448] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.122 seconds
[2021-02-19 07:44:08,195] {scheduler_job.py:182} INFO - Started process (PID=156) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:44:08,217] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:44:08,218] {logging_mixin.py:104} INFO - [2021-02-19 07:44:08,218] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:44:08,277] {logging_mixin.py:104} INFO - [2021-02-19 07:44:08,243] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 24, in <module>
    bash_command="echo 2"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 89, in __call__
    obj: BaseOperator = type.__call__(cls, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 122, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 410, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/task_group.py", line 140, in add
    raise DuplicateTaskIdFound(f"Task id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'bash' has already been added to the DAG
[2021-02-19 07:44:08,278] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:44:08,342] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.152 seconds
[2021-02-19 07:44:38,541] {scheduler_job.py:182} INFO - Started process (PID=166) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:44:38,543] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:44:38,544] {logging_mixin.py:104} INFO - [2021-02-19 07:44:38,544] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:44:38,588] {logging_mixin.py:104} INFO - [2021-02-19 07:44:38,586] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 24, in <module>
    bash_command="echo 2"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 89, in __call__
    obj: BaseOperator = type.__call__(cls, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 122, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 410, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/task_group.py", line 140, in add
    raise DuplicateTaskIdFound(f"Task id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'bash' has already been added to the DAG
[2021-02-19 07:44:38,593] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:44:38,635] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.107 seconds
[2021-02-19 07:44:58,088] {scheduler_job.py:182} INFO - Started process (PID=156) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:44:58,090] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:44:58,091] {logging_mixin.py:104} INFO - [2021-02-19 07:44:58,091] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:44:58,157] {logging_mixin.py:104} INFO - [2021-02-19 07:44:58,123] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 24, in <module>
    bash_command="echo 2"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 89, in __call__
    obj: BaseOperator = type.__call__(cls, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 122, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 404, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (bash 2) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2021-02-19 07:44:58,158] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:44:58,235] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.151 seconds
[2021-02-19 07:45:28,442] {scheduler_job.py:182} INFO - Started process (PID=166) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:45:28,443] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:45:28,444] {logging_mixin.py:104} INFO - [2021-02-19 07:45:28,444] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:45:28,459] {logging_mixin.py:104} INFO - [2021-02-19 07:45:28,456] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 24, in <module>
    bash_command="echo 2"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 89, in __call__
    obj: BaseOperator = type.__call__(cls, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 122, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 404, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (bash 2) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2021-02-19 07:45:28,460] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:45:28,564] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.128 seconds
[2021-02-19 07:45:59,497] {scheduler_job.py:182} INFO - Started process (PID=176) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:45:59,525] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:45:59,527] {logging_mixin.py:104} INFO - [2021-02-19 07:45:59,526] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:46:00,012] {logging_mixin.py:104} INFO - [2021-02-19 07:45:59,822] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 24, in <module>
    bash_command="echo 2"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 89, in __call__
    obj: BaseOperator = type.__call__(cls, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 122, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 404, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (bash 2) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2021-02-19 07:46:00,013] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:46:00,255] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.849 seconds
[2021-02-19 07:46:31,418] {scheduler_job.py:182} INFO - Started process (PID=186) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:46:31,524] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:46:31,526] {logging_mixin.py:104} INFO - [2021-02-19 07:46:31,525] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:46:33,893] {logging_mixin.py:104} INFO - [2021-02-19 07:46:33,888] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 24, in <module>
    bash_command="echo 2"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 89, in __call__
    obj: BaseOperator = type.__call__(cls, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 122, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 404, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (bash 2) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2021-02-19 07:46:33,894] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:46:34,023] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 2.610 seconds
[2021-02-19 07:47:05,721] {scheduler_job.py:182} INFO - Started process (PID=198) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:47:05,950] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:47:06,013] {logging_mixin.py:104} INFO - [2021-02-19 07:47:06,013] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:47:09,167] {logging_mixin.py:104} INFO - [2021-02-19 07:47:08,637] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 24, in <module>
    bash_command="echo 2"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 89, in __call__
    obj: BaseOperator = type.__call__(cls, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 122, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 404, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (bash 2) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2021-02-19 07:47:09,168] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:47:09,807] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 5.674 seconds
[2021-02-19 07:47:41,332] {scheduler_job.py:182} INFO - Started process (PID=205) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:47:41,392] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:47:41,440] {logging_mixin.py:104} INFO - [2021-02-19 07:47:41,394] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:47:41,719] {logging_mixin.py:104} INFO - [2021-02-19 07:47:41,626] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 24, in <module>
    bash_command="echo 2"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 89, in __call__
    obj: BaseOperator = type.__call__(cls, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 122, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 404, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (bash 2) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2021-02-19 07:47:41,721] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:47:42,278] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 1.003 seconds
[2021-02-19 07:48:12,726] {scheduler_job.py:182} INFO - Started process (PID=215) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:48:12,751] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:48:12,753] {logging_mixin.py:104} INFO - [2021-02-19 07:48:12,753] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:48:12,805] {logging_mixin.py:104} INFO - [2021-02-19 07:48:12,801] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 24, in <module>
    bash_command="echo 2"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 89, in __call__
    obj: BaseOperator = type.__call__(cls, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 122, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 404, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (bash 2) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2021-02-19 07:48:12,806] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:48:13,772] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 1.066 seconds
[2021-02-19 07:49:12,524] {scheduler_job.py:182} INFO - Started process (PID=155) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:49:12,568] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:49:12,569] {logging_mixin.py:104} INFO - [2021-02-19 07:49:12,568] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:49:12,684] {logging_mixin.py:104} INFO - [2021-02-19 07:49:12,683] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 32, in <module>
    bash_task_2.set_upstream(bask_task)
NameError: name 'bask_task' is not defined
[2021-02-19 07:49:12,687] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:49:12,875] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.364 seconds
[2021-02-19 07:49:43,015] {scheduler_job.py:182} INFO - Started process (PID=166) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:49:43,025] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:49:43,026] {logging_mixin.py:104} INFO - [2021-02-19 07:49:43,026] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:49:43,049] {logging_mixin.py:104} INFO - [2021-02-19 07:49:43,043] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 32, in <module>
    bash_task_2.set_upstream(bask_task)
NameError: name 'bask_task' is not defined
[2021-02-19 07:49:43,050] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:49:43,159] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.150 seconds
[2021-02-19 07:50:13,650] {scheduler_job.py:182} INFO - Started process (PID=176) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:50:13,672] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:50:13,674] {logging_mixin.py:104} INFO - [2021-02-19 07:50:13,673] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:50:14,012] {logging_mixin.py:104} INFO - [2021-02-19 07:50:13,991] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/ejemplo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ejemplo.py", line 32, in <module>
    bash_task_2.set_upstream(bask_task)
NameError: name 'bask_task' is not defined
[2021-02-19 07:50:14,013] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:50:14,394] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.776 seconds
[2021-02-19 07:50:44,808] {scheduler_job.py:182} INFO - Started process (PID=186) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:50:44,832] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:50:44,839] {logging_mixin.py:104} INFO - [2021-02-19 07:50:44,839] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:50:44,921] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['bash-task']) retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:50:44,964] {logging_mixin.py:104} INFO - [2021-02-19 07:50:44,964] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-19 07:50:44,980] {logging_mixin.py:104} INFO - [2021-02-19 07:50:44,980] {dag.py:1837} INFO - Creating ORM DAG for bash-task
[2021-02-19 07:50:44,988] {logging_mixin.py:104} INFO - [2021-02-19 07:50:44,988] {dag.py:2273} INFO - Setting next_dagrun for bash-task to 2021-02-17 00:00:00+00:00
[2021-02-19 07:50:45,299] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.497 seconds
[2021-02-19 07:51:16,160] {scheduler_job.py:182} INFO - Started process (PID=200) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:51:16,162] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:51:16,163] {logging_mixin.py:104} INFO - [2021-02-19 07:51:16,163] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:51:16,181] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['bash-task']) retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:51:16,220] {logging_mixin.py:104} INFO - [2021-02-19 07:51:16,220] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-19 07:51:16,249] {logging_mixin.py:104} INFO - [2021-02-19 07:51:16,249] {dag.py:2273} INFO - Setting next_dagrun for bash-task to 2021-02-17 00:00:00+00:00
[2021-02-19 07:51:16,262] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.109 seconds
[2021-02-19 07:51:46,514] {scheduler_job.py:182} INFO - Started process (PID=210) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:51:46,575] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:51:46,576] {logging_mixin.py:104} INFO - [2021-02-19 07:51:46,576] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:51:46,610] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['bash-task']) retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:51:46,666] {logging_mixin.py:104} INFO - [2021-02-19 07:51:46,665] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-19 07:51:46,703] {logging_mixin.py:104} INFO - [2021-02-19 07:51:46,703] {dag.py:2273} INFO - Setting next_dagrun for bash-task to 2021-02-17 00:00:00+00:00
[2021-02-19 07:51:46,733] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 0.238 seconds
[2021-02-19 07:52:17,452] {scheduler_job.py:182} INFO - Started process (PID=230) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:52:17,523] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:52:17,525] {logging_mixin.py:104} INFO - [2021-02-19 07:52:17,525] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:52:21,102] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['bash-task']) retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:52:27,460] {logging_mixin.py:104} INFO - [2021-02-19 07:52:27,459] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-19 07:52:29,413] {logging_mixin.py:104} INFO - [2021-02-19 07:52:29,413] {dag.py:2273} INFO - Setting next_dagrun for bash-task to 2021-02-17 08:00:00+00:00
[2021-02-19 07:52:30,336] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 13.114 seconds
[2021-02-19 07:53:02,112] {scheduler_job.py:182} INFO - Started process (PID=242) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:53:02,205] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:53:02,264] {logging_mixin.py:104} INFO - [2021-02-19 07:53:02,206] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:53:03,215] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['bash-task']) retrieved from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:53:03,585] {logging_mixin.py:104} INFO - [2021-02-19 07:53:03,585] {dag.py:1818} INFO - Sync 1 DAGs
[2021-02-19 07:53:17,527] {logging_mixin.py:104} INFO - [2021-02-19 07:53:17,527] {dag.py:2273} INFO - Setting next_dagrun for bash-task to 2021-02-17 08:00:00+00:00
[2021-02-19 07:53:22,144] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ejemplo.py took 20.038 seconds
[2021-02-19 07:54:01,903] {scheduler_job.py:182} INFO - Started process (PID=268) to work on /opt/airflow/dags/ejemplo.py
[2021-02-19 07:54:02,601] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/ejemplo.py for tasks to queue
[2021-02-19 07:54:03,099] {logging_mixin.py:104} INFO - [2021-02-19 07:54:03,083] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/ejemplo.py
[2021-02-19 07:54:37,801] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['bash-task']) retrieved from /opt/airflow/dags/ejemplo.py
