[2021-02-19 07:53:02,372] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: bash-task.bash 2021-02-17T05:00:00+00:00 [queued]>
[2021-02-19 07:53:02,944] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: bash-task.bash 2021-02-17T05:00:00+00:00 [queued]>
[2021-02-19 07:53:02,945] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-19 07:53:02,945] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-19 07:53:02,945] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-19 07:53:03,359] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): bash> on 2021-02-17T05:00:00+00:00
[2021-02-19 07:53:03,444] {standard_task_runner.py:52} INFO - Started process 252 to run task
[2021-02-19 07:53:03,604] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'bash-task', 'bash', '2021-02-17T05:00:00+00:00', '--job-id', '268', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ejemplo.py', '--cfg-path', '/tmp/tmpe5x6pzd7', '--error-file', '/tmp/tmpxi3qi7em']
[2021-02-19 07:53:03,659] {standard_task_runner.py:77} INFO - Job 268: Subtask bash
[2021-02-19 07:53:09,997] {logging_mixin.py:104} INFO - Running <TaskInstance: bash-task.bash 2021-02-17T05:00:00+00:00 [running]> on host 63b50af6ef7d
[2021-02-19 07:55:36,165] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=bash-task
AIRFLOW_CTX_TASK_ID=bash
AIRFLOW_CTX_EXECUTION_DATE=2021-02-17T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-17T05:00:00+00:00
[2021-02-19 07:55:37,473] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-02-19 07:55:38,439] {bash.py:158} INFO - Running command: echo 1
[2021-02-19 07:55:39,386] {local_task_job.py:77} ERROR - Received SIGTERM. Terminating subprocesses
[2021-02-19 07:55:39,781] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 252
[2021-02-19 07:55:39,844] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-02-19 07:55:39,845] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2021-02-19 07:55:41,180] {taskinstance.py:1455} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 166, in execute
    preexec_fn=pre_exec,
  File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1318, in _execute_child
    part = os.read(errpipe_read, 50000)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1241, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-02-19 07:55:46,931] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=bash-task, task_id=bash, execution_date=20210217T050000, start_date=20210219T075302, end_date=20210219T075546
